_commit: 0.0.2rc-214-gf428c12
_src_path: gh:skeleton-ci/skeleton-python
author: bswck
cli: true
copyright: Bartosz Sławecki
description: Scalable semi-automated code quality refining.
docs: true
email: bartoszpiotrslawecki@gmail.com
github: bswck
license: GPL-3.0
package: autorefine
precommit: true
pypi: true
pypi_description: Scalable semi-automated code quality refining.
pypi_project: autorefine
pypy: true
python: '3.8'
python_until: ''
repo: autorefine
rtd: autorefine
tests: true
tidelift: true
visibility: public
wip: true
