# docs https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/syntax-for-issue-forms
# https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/syntax-for-githubs-form-schema

name: Create a bug report
description: Errors and regression reports with complete reproducing test cases and/or stack traces.
body:
  - type: markdown
    attributes:
      value: "
**GUIDELINES FOR REPORTING BUGS**

1. A **brief description of the problem**—typically a line or two at most.

2. **Concise, dependency-free code which reproduces the problem**, otherwise known as a [Minimal, Complete, and Verifiable](https://stackoverflow.com/help/mcve) example.

3. **Complete stack traces for all errors—please use formatted text inside issues, not screenshots**.

4. Other things as applicable: **operating system**, **comparative performance timings** for performance issues.
"
  - type: textarea
    attributes:
      label: Describe the bug
      description: A clear and succinct description of what the bug is.
    validations:
      required: true

  - type: textarea
    attributes:
      label: To reproduce
      description: "
Provide your [Minimal, Complete, and Verifiable](https://stackoverflow.com/help/mcve) example here."
      placeholder: "# Insert code here"
      render: python
    validations:
      required: true

  - type: textarea
    attributes:
      label: Error
      description: "
Provide the complete text of any errors received **including the complete stack trace**.
If the message is a warning, run your program with the ``-Werror`` flag:   ``python -Werror myprogram.py``
"
      placeholder: "# Copy complete stack trace and error message here."
      value: "\
```

# Copy complete stack trace and error message here.

```
"
    validations:
      required: true

  - type: textarea
    attributes:
      label: Versions
      value: |
        - OS:
        - Python:
    validations:
      required: true

  - type: textarea
    attributes:
      label: Additional context
      description: Add any other context about the problem here.
    validations:
      required: false

  - type: markdown
    attributes:
      value: "**Have a great day!** 🌞"
