# docs https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/syntax-for-issue-forms
# https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/syntax-for-githubs-form-schema

name: Request a new functionality
description: Plan features for the library to implement in the future.
labels: [enhancement]
body:
  - type: textarea
    attributes:
      label: Use case
      description: A clear and concise description of what this feature will be useful for.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Example usage
      description: Provide a clear example of how the code using this functionality would look like.
    validations:
      required: false

  - type: textarea
    attributes:
      label: Additional context
      description: Add any other context about the use case here.
    validations:
      required: false

  - type: markdown
    attributes:
      value: "**Have an exciting day!**"
